package ca.sait.oosd.hibernate;
// Generated Aug 31, 2009 2:44:29 PM by Hibernate Tools 3.2.1.GA


import ca.sait.oosd.business.TEObject;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bookings generated by hbm2java
 */
public class Bookings extends TEObject implements java.io.Serializable {


     private long bookingid;
     private Packages packages;
     private Customers customers;
     private Triptypes triptypes;
     private Date bookingdate;
     private String bookingno;
     private Double travelercount;
     private Set<Bookingdetails> bookingdetailses = new HashSet<Bookingdetails>(0);

    public Bookings() {
    }

	
    public Bookings(long bookingid) {
        this.bookingid = bookingid;
    }
    public Bookings(long bookingid, Packages packages, Customers customers, Triptypes triptypes, Date bookingdate, String bookingno, Double travelercount, Set<Bookingdetails> bookingdetailses) {
       this.bookingid = bookingid;
       this.packages = packages;
       this.customers = customers;
       this.triptypes = triptypes;
       this.bookingdate = bookingdate;
       this.bookingno = bookingno;
       this.travelercount = travelercount;
       this.bookingdetailses = bookingdetailses;
    }
   
    public long getBookingid() {
        return this.bookingid;
    }
    
    public void setBookingid(long bookingid) {
        this.bookingid = bookingid;
    }
    public Packages getPackages() {
        return this.packages;
    }
    
    public void setPackages(Packages packages) {
        this.packages = packages;
    }
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }
    public Triptypes getTriptypes() {
        return this.triptypes;
    }
    
    public void setTriptypes(Triptypes triptypes) {
        this.triptypes = triptypes;
    }
    public Date getBookingdate() {
        return this.bookingdate;
    }
    
    public void setBookingdate(Date bookingdate) {
        this.bookingdate = bookingdate;
    }
    public String getBookingno() {
        return this.bookingno;
    }
    
    public void setBookingno(String bookingno) {
        this.bookingno = bookingno;
    }
    public Double getTravelercount() {
        return this.travelercount;
    }
    
    public void setTravelercount(Double travelercount) {
        this.travelercount = travelercount;
    }
    public Set<Bookingdetails> getBookingdetailses() {
        return this.bookingdetailses;
    }
    
    public void setBookingdetailses(Set<Bookingdetails> bookingdetailses) {
        this.bookingdetailses = bookingdetailses;
    }

    @Override
    public String toString() {
        return Long.toString(this.bookingid);
    }




}


