package ca.sait.oosd.hibernate;
// Generated Aug 31, 2009 2:44:29 PM by Hibernate Tools 3.2.1.GA


import ca.sait.oosd.business.TEObject;
import java.util.Date;

/**
 * Creditcards generated by hbm2java
 */
public class Creditcards extends TEObject implements java.io.Serializable {


     private long creditcardid;
     private Customers customers;
     private String ccname;
     private String ccnumber;
     private Date ccexpiry;

    public Creditcards() {
    }

    public Creditcards(long creditcardid, Customers customers, String ccname, String ccnumber, Date ccexpiry) {
       this.creditcardid = creditcardid;
       this.customers = customers;
       this.ccname = ccname;
       this.ccnumber = ccnumber;
       this.ccexpiry = ccexpiry;
    }
   
    public long getCreditcardid() {
        return this.creditcardid;
    }
    
    public void setCreditcardid(long creditcardid) {
        this.creditcardid = creditcardid;
    }
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }
    public String getCcname() {
        return this.ccname;
    }
    
    public void setCcname(String ccname) {
        this.ccname = ccname;
    }
    public String getCcnumber() {
        return this.ccnumber;
    }
    
    public void setCcnumber(String ccnumber) {
        this.ccnumber = ccnumber;
    }
    public Date getCcexpiry() {
        return this.ccexpiry;
    }
    
    public void setCcexpiry(Date ccexpiry) {
        this.ccexpiry = ccexpiry;
    }

    @Override
    public String toString() {
        return this.ccname;
    }




}


