package ca.sait.oosd.hibernate;
// Generated Aug 31, 2009 2:44:29 PM by Hibernate Tools 3.2.1.GA


import ca.sait.oosd.business.TEObject;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Packages generated by hbm2java
 */
public class Packages extends TEObject implements java.io.Serializable {


     private long packageid;
     private String pkgname;
     private Date pkgstartdate;
     private Date pkgenddate;
     private String pkgdesc;
     private BigDecimal pkgbaseprice;
     private BigDecimal pkgagencycommission;
     private Set<ProductsSuppliers> productsSupplierses = new HashSet<ProductsSuppliers>(0);
     private Set<Bookings> bookingses = new HashSet<Bookings>(0);

    public Packages() {
    }

	
    public Packages(long packageid, String pkgname, BigDecimal pkgbaseprice) {
        this.packageid = packageid;
        this.pkgname = pkgname;
        this.pkgbaseprice = pkgbaseprice;
    }
    public Packages(long packageid, String pkgname, Date pkgstartdate, Date pkgenddate, String pkgdesc, BigDecimal pkgbaseprice, BigDecimal pkgagencycommission, Set<ProductsSuppliers> productsSupplierses, Set<Bookings> bookingses) {
       this.packageid = packageid;
       this.pkgname = pkgname;
       this.pkgstartdate = pkgstartdate;
       this.pkgenddate = pkgenddate;
       this.pkgdesc = pkgdesc;
       this.pkgbaseprice = pkgbaseprice;
       this.pkgagencycommission = pkgagencycommission;
       this.productsSupplierses = productsSupplierses;
       this.bookingses = bookingses;
    }
   
    public long getPackageid() {
        return this.packageid;
    }
    
    public void setPackageid(long packageid) {
        this.packageid = packageid;
    }
    public String getPkgname() {
        return this.pkgname;
    }
    
    public void setPkgname(String pkgname) {
        this.pkgname = pkgname;
    }
    public Date getPkgstartdate() {
        return this.pkgstartdate;
    }
    
    public void setPkgstartdate(Date pkgstartdate) {
        this.pkgstartdate = pkgstartdate;
    }
    public Date getPkgenddate() {
        return this.pkgenddate;
    }
    
    public void setPkgenddate(Date pkgenddate) {
        this.pkgenddate = pkgenddate;
    }
    public String getPkgdesc() {
        return this.pkgdesc;
    }
    
    public void setPkgdesc(String pkgdesc) {
        this.pkgdesc = pkgdesc;
    }
    public BigDecimal getPkgbaseprice() {
        return this.pkgbaseprice;
    }
    
    public void setPkgbaseprice(BigDecimal pkgbaseprice) {
        this.pkgbaseprice = pkgbaseprice;
    }
    public BigDecimal getPkgagencycommission() {
        return this.pkgagencycommission;
    }
    
    public void setPkgagencycommission(BigDecimal pkgagencycommission) {
        this.pkgagencycommission = pkgagencycommission;
    }
    public Set<ProductsSuppliers> getProductsSupplierses() {
        return this.productsSupplierses;
    }
    
    public void setProductsSupplierses(Set<ProductsSuppliers> productsSupplierses) {
        this.productsSupplierses = productsSupplierses;
    }
    public Set<Bookings> getBookingses() {
        return this.bookingses;
    }
    
    public void setBookingses(Set<Bookings> bookingses) {
        this.bookingses = bookingses;
    }

    @Override
    public String toString() {
        return this.pkgname;
    }




}


