package ca.sait.oosd.hibernate;
// Generated Aug 31, 2009 2:44:29 PM by Hibernate Tools 3.2.1.GA


import ca.sait.oosd.business.TEObject;
import java.util.HashSet;
import java.util.Set;

/**
 * Triptypes generated by hbm2java
 */
public class Triptypes extends TEObject implements java.io.Serializable {


     private String triptypeid;
     private String ttname;
     private Set<Bookings> bookingses = new HashSet<Bookings>(0);

    public Triptypes() {
    }

	
    public Triptypes(String triptypeid) {
        this.triptypeid = triptypeid;
    }
    public Triptypes(String triptypeid, String ttname, Set<Bookings> bookingses) {
       this.triptypeid = triptypeid;
       this.ttname = ttname;
       this.bookingses = bookingses;
    }
   
    public String getTriptypeid() {
        return this.triptypeid;
    }
    
    public void setTriptypeid(String triptypeid) {
        this.triptypeid = triptypeid;
    }
    public String getTtname() {
        return this.ttname;
    }
    
    public void setTtname(String ttname) {
        this.ttname = ttname;
    }
    public Set<Bookings> getBookingses() {
        return this.bookingses;
    }
    
    public void setBookingses(Set<Bookings> bookingses) {
        this.bookingses = bookingses;
    }

    @Override
    public String toString() {
        throw new UnsupportedOperationException("Not supported yet.");
    }




}


