package ca.sait.oosd.hibernate;
// Generated Aug 31, 2009 2:44:29 PM by Hibernate Tools 3.2.1.GA


import ca.sait.oosd.business.TEObject;
import java.util.HashSet;
import java.util.Set;

/**
 * Affiliations generated by hbm2java
 */
public class Affiliations extends TEObject implements java.io.Serializable {


     private String affilitationid;
     private String affname;
     private String affdesc;
     private Set<Suppliercontacts> suppliercontactses = new HashSet<Suppliercontacts>(0);

    public Affiliations() {
    }

	
    public Affiliations(String affilitationid) {
        this.affilitationid = affilitationid;
    }
    public Affiliations(String affilitationid, String affname, String affdesc, Set<Suppliercontacts> suppliercontactses) {
       this.affilitationid = affilitationid;
       this.affname = affname;
       this.affdesc = affdesc;
       this.suppliercontactses = suppliercontactses;
    }
   
    public String getAffilitationid() {
        return this.affilitationid;
    }
    
    public void setAffilitationid(String affilitationid) {
        this.affilitationid = affilitationid;
    }
    public String getAffname() {
        return this.affname;
    }
    
    public void setAffname(String affname) {
        this.affname = affname;
    }
    public String getAffdesc() {
        return this.affdesc;
    }
    
    public void setAffdesc(String affdesc) {
        this.affdesc = affdesc;
    }
    public Set<Suppliercontacts> getSuppliercontactses() {
        return this.suppliercontactses;
    }
    
    public void setSuppliercontactses(Set<Suppliercontacts> suppliercontactses) {
        this.suppliercontactses = suppliercontactses;
    }

    @Override
    public String toString() {
        return this.affname;
    }




}


