package ca.sait.oosd.hibernate;
// Generated Aug 31, 2009 2:44:29 PM by Hibernate Tools 3.2.1.GA


import ca.sait.oosd.business.TEObject;
import java.util.HashSet;
import java.util.Set;

/**
 * Agents generated by hbm2java
 */
public class Agents extends TEObject implements java.io.Serializable {


     private long agentid;
     private Agencies agencies;
     private String agtfirstname;
     private String agtmiddleinitial;
     private String agtlastname;
     private String agtbusphone;
     private String agtemail;
     private String agtposition;
     private Set<Customers> customerses = new HashSet<Customers>(0);

    public Agents() {
    }

	
    public Agents(long agentid) {
        this.agentid = agentid;
    }
    public Agents(long agentid, Agencies agencies, String agtfirstname, String agtmiddleinitial, String agtlastname, String agtbusphone, String agtemail, String agtposition, Set<Customers> customerses) {
       this.agentid = agentid;
       this.agencies = agencies;
       this.agtfirstname = agtfirstname;
       this.agtmiddleinitial = agtmiddleinitial;
       this.agtlastname = agtlastname;
       this.agtbusphone = agtbusphone;
       this.agtemail = agtemail;
       this.agtposition = agtposition;
       this.customerses = customerses;
    }
   
    public long getAgentid() {
        return this.agentid;
    }
    
    public void setAgentid(long agentid) {
        this.agentid = agentid;
    }
    public Agencies getAgencies() {
        return this.agencies;
    }
    
    public void setAgencies(Agencies agencies) {
        this.agencies = agencies;
    }
    public String getAgtfirstname() {
        return this.agtfirstname;
    }
    
    public void setAgtfirstname(String agtfirstname) {
        this.agtfirstname = agtfirstname;
    }
    public String getAgtmiddleinitial() {
        return this.agtmiddleinitial;
    }
    
    public void setAgtmiddleinitial(String agtmiddleinitial) {
        this.agtmiddleinitial = agtmiddleinitial;
    }
    public String getAgtlastname() {
        return this.agtlastname;
    }
    
    public void setAgtlastname(String agtlastname) {
        this.agtlastname = agtlastname;
    }
    public String getAgtbusphone() {
        return this.agtbusphone;
    }
    
    public void setAgtbusphone(String agtbusphone) {
        this.agtbusphone = agtbusphone;
    }
    public String getAgtemail() {
        return this.agtemail;
    }
    
    public void setAgtemail(String agtemail) {
        this.agtemail = agtemail;
    }
    public String getAgtposition() {
        return this.agtposition;
    }
    
    public void setAgtposition(String agtposition) {
        this.agtposition = agtposition;
    }
    public Set<Customers> getCustomerses() {
        return this.customerses;
    }
    
    public void setCustomerses(Set<Customers> customerses) {
        this.customerses = customerses;
    }

    @Override
    public String toString() {
        return this.agtfirstname + " " + this.agtmiddleinitial + ", " + this.agtlastname;
    }




}


