package ca.sait.oosd.hibernate;
// Generated Aug 31, 2009 2:44:29 PM by Hibernate Tools 3.2.1.GA


import ca.sait.oosd.business.TEObject;
import java.util.HashSet;
import java.util.Set;

/**
 * Agencies generated by hbm2java
 */
public class Agencies extends TEObject implements java.io.Serializable {


     private long agencyid;
     private String agncyaddress;
     private String agncycity;
     private String agncyprov;
     private String agncypostal;
     private String agncycountry;
     private String agncyphone;
     private String agncyfax;
     private Set<Agents> agentses = new HashSet<Agents>(0);

    public Agencies() {
    }

	
    public Agencies(long agencyid) {
        this.agencyid = agencyid;
    }
    public Agencies(long agencyid, String agncyaddress, String agncycity, String agncyprov, String agncypostal, String agncycountry, String agncyphone, String agncyfax, Set<Agents> agentses) {
       this.agencyid = agencyid;
       this.agncyaddress = agncyaddress;
       this.agncycity = agncycity;
       this.agncyprov = agncyprov;
       this.agncypostal = agncypostal;
       this.agncycountry = agncycountry;
       this.agncyphone = agncyphone;
       this.agncyfax = agncyfax;
       this.agentses = agentses;
    }
   
    public long getAgencyid() {
        return this.agencyid;
    }
    
    public void setAgencyid(long agencyid) {
        this.agencyid = agencyid;
    }
    public String getAgncyaddress() {
        return this.agncyaddress;
    }
    
    public void setAgncyaddress(String agncyaddress) {
        this.agncyaddress = agncyaddress;
    }
    public String getAgncycity() {
        return this.agncycity;
    }
    
    public void setAgncycity(String agncycity) {
        this.agncycity = agncycity;
    }
    public String getAgncyprov() {
        return this.agncyprov;
    }
    
    public void setAgncyprov(String agncyprov) {
        this.agncyprov = agncyprov;
    }
    public String getAgncypostal() {
        return this.agncypostal;
    }
    
    public void setAgncypostal(String agncypostal) {
        this.agncypostal = agncypostal;
    }
    public String getAgncycountry() {
        return this.agncycountry;
    }
    
    public void setAgncycountry(String agncycountry) {
        this.agncycountry = agncycountry;
    }
    public String getAgncyphone() {
        return this.agncyphone;
    }
    
    public void setAgncyphone(String agncyphone) {
        this.agncyphone = agncyphone;
    }
    public String getAgncyfax() {
        return this.agncyfax;
    }
    
    public void setAgncyfax(String agncyfax) {
        this.agncyfax = agncyfax;
    }
    public Set<Agents> getAgentses() {
        return this.agentses;
    }
    
    public void setAgentses(Set<Agents> agentses) {
        this.agentses = agentses;
    }

    @Override
    public String toString() {
        return Long.toString(this.agencyid);
    }




}


