package ca.sait.oosd.hibernate;
// Generated Aug 31, 2009 2:44:29 PM by Hibernate Tools 3.2.1.GA

import ca.sait.oosd.business.TEObject;




/**
 * CustomersRewards generated by hbm2java
 */
public class CustomersRewards extends TEObject implements java.io.Serializable {


     private CustomersRewardsId id;
     private Customers customers;
     private Rewards rewards;
     private String rwdnumber;

    public CustomersRewards() {
    }

    public CustomersRewards(CustomersRewardsId id, Customers customers, Rewards rewards, String rwdnumber) {
       this.id = id;
       this.customers = customers;
       this.rewards = rewards;
       this.rwdnumber = rwdnumber;
    }
   
    public CustomersRewardsId getId() {
        return this.id;
    }
    
    public void setId(CustomersRewardsId id) {
        this.id = id;
    }
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }
    public Rewards getRewards() {
        return this.rewards;
    }
    
    public void setRewards(Rewards rewards) {
        this.rewards = rewards;
    }
    public String getRwdnumber() {
        return this.rwdnumber;
    }
    
    public void setRwdnumber(String rwdnumber) {
        this.rwdnumber = rwdnumber;
    }

    @Override
    public String toString() {
        return this.rwdnumber;
    }




}


