package ca.sait.oosd.hibernate;
// Generated Aug 31, 2009 2:44:29 PM by Hibernate Tools 3.2.1.GA


import ca.sait.oosd.business.TEObject;
import java.util.HashSet;
import java.util.Set;

/**
 * Rewards generated by hbm2java
 */
public class Rewards extends TEObject implements java.io.Serializable {


     private long rewardid;
     private String rwdname;
     private String rwddesc;
     private Set<CustomersRewards> customersRewardses = new HashSet<CustomersRewards>(0);

    public Rewards() {
    }

	
    public Rewards(long rewardid) {
        this.rewardid = rewardid;
    }
    public Rewards(long rewardid, String rwdname, String rwddesc, Set<CustomersRewards> customersRewardses) {
       this.rewardid = rewardid;
       this.rwdname = rwdname;
       this.rwddesc = rwddesc;
       this.customersRewardses = customersRewardses;
    }
   
    public long getRewardid() {
        return this.rewardid;
    }
    
    public void setRewardid(long rewardid) {
        this.rewardid = rewardid;
    }
    public String getRwdname() {
        return this.rwdname;
    }
    
    public void setRwdname(String rwdname) {
        this.rwdname = rwdname;
    }
    public String getRwddesc() {
        return this.rwddesc;
    }
    
    public void setRwddesc(String rwddesc) {
        this.rwddesc = rwddesc;
    }
    public Set<CustomersRewards> getCustomersRewardses() {
        return this.customersRewardses;
    }
    
    public void setCustomersRewardses(Set<CustomersRewards> customersRewardses) {
        this.customersRewardses = customersRewardses;
    }

    @Override
    public String toString() {
        throw new UnsupportedOperationException("Not supported yet.");
    }




}


