package ca.sait.oosd.hibernate;
// Generated Aug 31, 2009 2:44:29 PM by Hibernate Tools 3.2.1.GA

import ca.sait.oosd.business.TEObject;




/**
 * Suppliercontacts generated by hbm2java
 */
public class Suppliercontacts extends TEObject implements java.io.Serializable {


     private long suppliercontactid;
     private Affiliations affiliations;
     private Suppliers suppliers;
     private String supconfirstname;
     private String supconlastname;
     private String supconcompany;
     private String supconaddress;
     private String supconcity;
     private String supconprov;
     private String supconpostal;
     private String supconcountry;
     private String supconbusphone;
     private String supconfax;
     private String supconemail;
     private String supconurl;

    public Suppliercontacts() {
    }

	
    public Suppliercontacts(long suppliercontactid) {
        this.suppliercontactid = suppliercontactid;
    }
    public Suppliercontacts(long suppliercontactid, Affiliations affiliations, Suppliers suppliers, String supconfirstname, String supconlastname, String supconcompany, String supconaddress, String supconcity, String supconprov, String supconpostal, String supconcountry, String supconbusphone, String supconfax, String supconemail, String supconurl) {
       this.suppliercontactid = suppliercontactid;
       this.affiliations = affiliations;
       this.suppliers = suppliers;
       this.supconfirstname = supconfirstname;
       this.supconlastname = supconlastname;
       this.supconcompany = supconcompany;
       this.supconaddress = supconaddress;
       this.supconcity = supconcity;
       this.supconprov = supconprov;
       this.supconpostal = supconpostal;
       this.supconcountry = supconcountry;
       this.supconbusphone = supconbusphone;
       this.supconfax = supconfax;
       this.supconemail = supconemail;
       this.supconurl = supconurl;
    }
   
    public long getSuppliercontactid() {
        return this.suppliercontactid;
    }
    
    public void setSuppliercontactid(long suppliercontactid) {
        this.suppliercontactid = suppliercontactid;
    }
    public Affiliations getAffiliations() {
        return this.affiliations;
    }
    
    public void setAffiliations(Affiliations affiliations) {
        this.affiliations = affiliations;
    }
    public Suppliers getSuppliers() {
        return this.suppliers;
    }
    
    public void setSuppliers(Suppliers suppliers) {
        this.suppliers = suppliers;
    }
    public String getSupconfirstname() {
        return this.supconfirstname;
    }
    
    public void setSupconfirstname(String supconfirstname) {
        this.supconfirstname = supconfirstname;
    }
    public String getSupconlastname() {
        return this.supconlastname;
    }
    
    public void setSupconlastname(String supconlastname) {
        this.supconlastname = supconlastname;
    }
    public String getSupconcompany() {
        return this.supconcompany;
    }
    
    public void setSupconcompany(String supconcompany) {
        this.supconcompany = supconcompany;
    }
    public String getSupconaddress() {
        return this.supconaddress;
    }
    
    public void setSupconaddress(String supconaddress) {
        this.supconaddress = supconaddress;
    }
    public String getSupconcity() {
        return this.supconcity;
    }
    
    public void setSupconcity(String supconcity) {
        this.supconcity = supconcity;
    }
    public String getSupconprov() {
        return this.supconprov;
    }
    
    public void setSupconprov(String supconprov) {
        this.supconprov = supconprov;
    }
    public String getSupconpostal() {
        return this.supconpostal;
    }
    
    public void setSupconpostal(String supconpostal) {
        this.supconpostal = supconpostal;
    }
    public String getSupconcountry() {
        return this.supconcountry;
    }
    
    public void setSupconcountry(String supconcountry) {
        this.supconcountry = supconcountry;
    }
    public String getSupconbusphone() {
        return this.supconbusphone;
    }
    
    public void setSupconbusphone(String supconbusphone) {
        this.supconbusphone = supconbusphone;
    }
    public String getSupconfax() {
        return this.supconfax;
    }
    
    public void setSupconfax(String supconfax) {
        this.supconfax = supconfax;
    }
    public String getSupconemail() {
        return this.supconemail;
    }
    
    public void setSupconemail(String supconemail) {
        this.supconemail = supconemail;
    }
    public String getSupconurl() {
        return this.supconurl;
    }
    
    public void setSupconurl(String supconurl) {
        this.supconurl = supconurl;
    }

    @Override
    public String toString() {
        throw new UnsupportedOperationException("Not supported yet.");
    }




}


