package ca.sait.oosd.hibernate;
// Generated Aug 31, 2009 2:44:29 PM by Hibernate Tools 3.2.1.GA


import ca.sait.oosd.business.TEObject;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Bookingdetails generated by hbm2java
 */
public class Bookingdetails extends TEObject implements java.io.Serializable {


     private long bookingdetailid;
     private ProductsSuppliers productsSuppliers;
     private Fees fees;
     private Classes classes;
     private Regions regions;
     private Bookings bookings;
     private Double itineraryno;
     private Date tripstart;
     private Date tripend;
     private String description;
     private String destination;
     private BigDecimal baseprice;
     private BigDecimal agencycommission;

    public Bookingdetails() {
    }

	
    public Bookingdetails(long bookingdetailid) {
        this.bookingdetailid = bookingdetailid;
    }
    public Bookingdetails(long bookingdetailid, ProductsSuppliers productsSuppliers, Fees fees, Classes classes, Regions regions, Bookings bookings, Double itineraryno, Date tripstart, Date tripend, String description, String destination, BigDecimal baseprice, BigDecimal agencycommission) {
       this.bookingdetailid = bookingdetailid;
       this.productsSuppliers = productsSuppliers;
       this.fees = fees;
       this.classes = classes;
       this.regions = regions;
       this.bookings = bookings;
       this.itineraryno = itineraryno;
       this.tripstart = tripstart;
       this.tripend = tripend;
       this.description = description;
       this.destination = destination;
       this.baseprice = baseprice;
       this.agencycommission = agencycommission;
    }
   
    public long getBookingdetailid() {
        return this.bookingdetailid;
    }
    
    public void setBookingdetailid(long bookingdetailid) {
        this.bookingdetailid = bookingdetailid;
    }
    public ProductsSuppliers getProductsSuppliers() {
        return this.productsSuppliers;
    }
    
    public void setProductsSuppliers(ProductsSuppliers productsSuppliers) {
        this.productsSuppliers = productsSuppliers;
    }
    public Fees getFees() {
        return this.fees;
    }
    
    public void setFees(Fees fees) {
        this.fees = fees;
    }
    public Classes getClasses() {
        return this.classes;
    }
    
    public void setClasses(Classes classes) {
        this.classes = classes;
    }
    public Regions getRegions() {
        return this.regions;
    }
    
    public void setRegions(Regions regions) {
        this.regions = regions;
    }
    public Bookings getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Bookings bookings) {
        this.bookings = bookings;
    }
    public Double getItineraryno() {
        return this.itineraryno;
    }
    
    public void setItineraryno(Double itineraryno) {
        this.itineraryno = itineraryno;
    }
    public Date getTripstart() {
        return this.tripstart;
    }
    
    public void setTripstart(Date tripstart) {
        this.tripstart = tripstart;
    }
    public Date getTripend() {
        return this.tripend;
    }
    
    public void setTripend(Date tripend) {
        this.tripend = tripend;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getDestination() {
        return this.destination;
    }
    
    public void setDestination(String destination) {
        this.destination = destination;
    }
    public BigDecimal getBaseprice() {
        return this.baseprice;
    }
    
    public void setBaseprice(BigDecimal baseprice) {
        this.baseprice = baseprice;
    }
    public BigDecimal getAgencycommission() {
        return this.agencycommission;
    }
    
    public void setAgencycommission(BigDecimal agencycommission) {
        this.agencycommission = agencycommission;
    }

    @Override
    public String toString() {
        return Long.toString(this.bookingdetailid);
    }




}


