package ca.sait.oosd.hibernate;
// Generated Aug 31, 2009 2:44:29 PM by Hibernate Tools 3.2.1.GA


import ca.sait.oosd.business.TEObject;
import java.util.HashSet;
import java.util.Set;

/**
 * Classes generated by hbm2java
 */
public class Classes extends TEObject implements java.io.Serializable {


     private String classid;
     private String classname;
     private String classdesc;
     private Set<Bookingdetails> bookingdetailses = new HashSet<Bookingdetails>(0);

    public Classes() {
    }

	
    public Classes(String classid, String classname) {
        this.classid = classid;
        this.classname = classname;
    }
    public Classes(String classid, String classname, String classdesc, Set<Bookingdetails> bookingdetailses) {
       this.classid = classid;
       this.classname = classname;
       this.classdesc = classdesc;
       this.bookingdetailses = bookingdetailses;
    }
   
    public String getClassid() {
        return this.classid;
    }
    
    public void setClassid(String classid) {
        this.classid = classid;
    }
    public String getClassname() {
        return this.classname;
    }
    
    public void setClassname(String classname) {
        this.classname = classname;
    }
    public String getClassdesc() {
        return this.classdesc;
    }
    
    public void setClassdesc(String classdesc) {
        this.classdesc = classdesc;
    }
    public Set<Bookingdetails> getBookingdetailses() {
        return this.bookingdetailses;
    }
    
    public void setBookingdetailses(Set<Bookingdetails> bookingdetailses) {
        this.bookingdetailses = bookingdetailses;
    }

    @Override
    public String toString() {
        return this.classname;
    }




}


