package ca.sait.oosd.hibernate;
// Generated Aug 31, 2009 2:44:29 PM by Hibernate Tools 3.2.1.GA


import ca.sait.oosd.business.TEObject;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductsSuppliers generated by hbm2java
 */
public class ProductsSuppliers extends TEObject implements java.io.Serializable {


     private long productsupplierid;
     private Products products;
     private Suppliers suppliers;
     private Set<Bookingdetails> bookingdetailses = new HashSet<Bookingdetails>(0);
     private Set<Packages> packageses = new HashSet<Packages>(0);

    public ProductsSuppliers() {
    }

	
    public ProductsSuppliers(long productsupplierid) {
        this.productsupplierid = productsupplierid;
    }
    public ProductsSuppliers(long productsupplierid, Products products, Suppliers suppliers, Set<Bookingdetails> bookingdetailses, Set<Packages> packageses) {
       this.productsupplierid = productsupplierid;
       this.products = products;
       this.suppliers = suppliers;
       this.bookingdetailses = bookingdetailses;
       this.packageses = packageses;
    }
   
    public long getProductsupplierid() {
        return this.productsupplierid;
    }
    
    public void setProductsupplierid(long productsupplierid) {
        this.productsupplierid = productsupplierid;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public Suppliers getSuppliers() {
        return this.suppliers;
    }
    
    public void setSuppliers(Suppliers suppliers) {
        this.suppliers = suppliers;
    }
    public Set<Bookingdetails> getBookingdetailses() {
        return this.bookingdetailses;
    }
    
    public void setBookingdetailses(Set<Bookingdetails> bookingdetailses) {
        this.bookingdetailses = bookingdetailses;
    }
    public Set<Packages> getPackageses() {
        return this.packageses;
    }
    
    public void setPackageses(Set<Packages> packageses) {
        this.packageses = packageses;
    }

    @Override
    public String toString() {
        throw new UnsupportedOperationException("Not supported yet.");
    }




}


