package ca.sait.oosd.hibernate;
// Generated Aug 31, 2009 2:44:29 PM by Hibernate Tools 3.2.1.GA


import ca.sait.oosd.business.TEObject;
import java.util.HashSet;
import java.util.Set;

/**
 * Suppliers generated by hbm2java
 */
public class Suppliers extends TEObject implements java.io.Serializable {


     private long supplierid;
     private String supname;
     private Set<Suppliercontacts> suppliercontactses = new HashSet<Suppliercontacts>(0);
     private Set<ProductsSuppliers> productsSupplierses = new HashSet<ProductsSuppliers>(0);

    public Suppliers() {
    }

	
    public Suppliers(long supplierid) {
        this.supplierid = supplierid;
    }
    public Suppliers(long supplierid, String supname, Set<Suppliercontacts> suppliercontactses, Set<ProductsSuppliers> productsSupplierses) {
       this.supplierid = supplierid;
       this.supname = supname;
       this.suppliercontactses = suppliercontactses;
       this.productsSupplierses = productsSupplierses;
    }
   
    public long getSupplierid() {
        return this.supplierid;
    }
    
    public void setSupplierid(long supplierid) {
        this.supplierid = supplierid;
    }
    public String getSupname() {
        return this.supname;
    }
    
    public void setSupname(String supname) {
        this.supname = supname;
    }
    public Set<Suppliercontacts> getSuppliercontactses() {
        return this.suppliercontactses;
    }
    
    public void setSuppliercontactses(Set<Suppliercontacts> suppliercontactses) {
        this.suppliercontactses = suppliercontactses;
    }
    public Set<ProductsSuppliers> getProductsSupplierses() {
        return this.productsSupplierses;
    }
    
    public void setProductsSupplierses(Set<ProductsSuppliers> productsSupplierses) {
        this.productsSupplierses = productsSupplierses;
    }

    @Override
    public String toString() {
        return this.supname;
    }




}


