package ca.sait.oosd.hibernate;
// Generated Aug 31, 2009 2:44:29 PM by Hibernate Tools 3.2.1.GA

import ca.sait.oosd.business.TEObject;




/**
 * CustomersRewardsId generated by hbm2java
 */
public class CustomersRewardsId extends TEObject implements java.io.Serializable {


     private long customerid;
     private long rewardid;

    public CustomersRewardsId() {
    }

    public CustomersRewardsId(long customerid, long rewardid) {
       this.customerid = customerid;
       this.rewardid = rewardid;
    }
   
    public long getCustomerid() {
        return this.customerid;
    }
    
    public void setCustomerid(long customerid) {
        this.customerid = customerid;
    }
    public long getRewardid() {
        return this.rewardid;
    }
    
    public void setRewardid(long rewardid) {
        this.rewardid = rewardid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CustomersRewardsId) ) return false;
		 CustomersRewardsId castOther = ( CustomersRewardsId ) other; 
         
		 return (this.getCustomerid()==castOther.getCustomerid())
 && (this.getRewardid()==castOther.getRewardid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCustomerid();
         result = 37 * result + (int) this.getRewardid();
         return result;
   }

    @Override
    public String toString() {
        throw new UnsupportedOperationException("Not supported yet.");
    }


}


