package ca.sait.oosd.hibernate;
// Generated Aug 31, 2009 2:44:29 PM by Hibernate Tools 3.2.1.GA


import ca.sait.oosd.business.TEObject;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products extends TEObject implements java.io.Serializable {


     private long productid;
     private String prodname;
     private Set<ProductsSuppliers> productsSupplierses = new HashSet<ProductsSuppliers>(0);

    public Products() {
    }

	
    public Products(long productid, String prodname) {
        this.productid = productid;
        this.prodname = prodname;
    }
    public Products(long productid, String prodname, Set<ProductsSuppliers> productsSupplierses) {
       this.productid = productid;
       this.prodname = prodname;
       this.productsSupplierses = productsSupplierses;
    }
   
    public long getProductid() {
        return this.productid;
    }
    
    public void setProductid(long productid) {
        this.productid = productid;
    }
    public String getProdname() {
        return this.prodname;
    }
    
    public void setProdname(String prodname) {
        this.prodname = prodname;
    }
    public Set<ProductsSuppliers> getProductsSupplierses() {
        return this.productsSupplierses;
    }
    
    public void setProductsSupplierses(Set<ProductsSuppliers> productsSupplierses) {
        this.productsSupplierses = productsSupplierses;
    }

    @Override
    public String toString() {
        return this.prodname;
    }




}


